name: Build
on:
    push:
        branches:
            - branch-5.0
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: 11
                  distribution: 'adopt'
            - name: Cache SonarCloud packages
              uses: actions/cache@v3
              with:
                  path: ~/.sonar/cache
                  key: ${{ runner.os }}-sonar
                  restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Check code formatting
              run: mvn -B spotless:check
            - name: Build, test, analyze
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: mvn -B -Pcoverage verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    tck:
        name: TCK
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: 11
                    distribution: 'adopt'
            -   name: Cache Maven packages
                uses: actions/cache@v3
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2
            -   name: Cache Docker images
                uses: satackey/action-docker-layer-caching@v0.0.11
                continue-on-error: true
            -   name: Run TCK for OAI-PMH 2.0 compliance
                run: mvn -B -pl 'xoai-data-provider-tck' -am verify
